security:
  ignore:
    whites:
      - /auth/code
      - /auth/logout
      - /auth/login
      - /*/v3/api-docs
      - /*/error
      - /csrf

spring:
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true

          routes:
            # 认证模块
            - id: auth_route
              uri: lb://auth-service          # lb:// 代表从注册中心负载均衡
              predicates:
                - Path=/auth/** # 匹配规则
              filters:
                - StripPrefix=1
            # 系统模块
            - id: system_route
              uri: lb://system-system
              predicates:
                - Path=/system/**
              filters:
                - StripPrefix=1